pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                echo 'Compiling Java file...'
                sh 'javac sample_repository/sample_maven_project/src/test/java/sample_package/SampleClass.java'
            }
        }
        stage('Run Java Program') {
            steps {
                echo 'Running Java program...'
                sh 'java sample_repository/sample_maven_project/src/test/java/sample_package/SampleClass'
            }
        }
    }
}
